[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
startCommand = "npm start"
numReplicas = 1

[service]
rootDirectory = "."
internalPort = 8080 