[build]
builder = "nixpacks"
buildCommand = "cd backend && npm install"
providers = ["node"]

[deploy]
startCommand = "cd backend && node server/server.js"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[service]
rootDirectory = "backend"

[nixpacks]
nodejs = "18" 